name: niks
description: A lib that helps you create layer oriented canvas applications
version: 0.0.2
author: Renan C. Araújo <renan@caraujo.me>
homepage: https://github.com/renancaraujo/niks

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  uuid: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

