name: niks_bitmap
description: Use niks with bitmap layers
version: 0.0.2-next
author: Renan C. Araújo <renan@caraujo.me>
homepage: https://github.com/renancaraujo/niks

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bitmap: ^0.0.4-next2
  niks: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: